<?php
/**
 * @category    Katapult
 * @package     Katapult_Payment
 */

/** @var \Katapult\Payment\Block\Jsplugin $block */
if ($block->config->isEnable()): ?>
    <script type='text/javascript'>
        require(['jquery'], function ($) {
            var _katapult_config = {
                api_key: '<?= /* @noEscape */ $block->config->getPublicToken() ?>',
                environment: '<?= /* @noEscape */ $block->config->getEnvironment() ?>'
            };

            !function (e, t) {
                e.katapult = e.katapult || {};
                var n, i, r;
                i = !1, n = document.createElement('script'),
                    n.type = 'text/javascript',
                    n.async = !0,
                    n.src = t.environment + '/' + 'plugin/js/katapult.js',
                    n.onload = n.onreadystatechange = function () {
                    i || this.readyState && 'complete' != this.readyState || (i = !0, e.katapult.setConfig(t.api_key))
                }, r = document.getElementsByTagName('script')[0], r.parentNode.insertBefore(n, r);
                var s = document.createElement('link');
                s.setAttribute('rel', 'stylesheet'),
                    s.setAttribute('type', 'text/css'),
                    s.setAttribute('href', t.environment + '/' + 'plugin/css/katapult.css');
                var a = document.querySelector('head');
                a.insertBefore(s, a.firstChild)
            }(window, _katapult_config);

            $(document).ready(function ($) {
                $('.btn-katapult-preapprove').on('click', function () {
                    katapult.preapprove();
                });
            });
        });
    </script>
<?php endif; ?>
